version: 0.0
os: linux

files:
  - source: /index.html
    destination: /var/www/html/

hooks:
  ApplicationStop:
    - location: stop_server
      timeout: 300
      runas: root

  BeforeInstall:
    - location: install_dependencies
      timeout: 300
      runas: root

  ApplicationStart:
    - location: start_server
      timeout: 300
      runas: root
